# Workflow de CI para ejecutar pruebas automatizadas con Playwright y publicar reportes (HTML y Allure) en GitHub Pages
name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      # Descarga el código fuente del repositorio
      - uses: actions/checkout@v4

      # Configura Node.js en la versión LTS más reciente
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      # Instala todas las dependencias del proyecto (npm install)
      - name: Install dependencies
        run: npm ci

      # Instala los navegadores necesarios para Playwright (Chromium, Firefox, WebKit)
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      # Ejecuta las pruebas automatizadas de Playwright
      - name: Run Playwright tests
        run: npx playwright test

      # Sube el reporte HTML de Playwright como artefacto descargable en GitHub Actions
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      # Deploya el reporte de Playwright
      - name: Deploy Playwright report to GitHub Pages
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./playwright-report
          publish_branch: gh-pages
          destination_dir: playwright/${{ github.run_number }}
          force_orphan: false
      # Instala el CLI de Allure       
      - name: Install Allure CLI
        run: npm install -g allure-commandline --save-dev
      # Genera el reporte de allure
      - name: Generate Allure report
        run: allure generate allure-results --clean -o allure-report

      # Deploya el reporte de allure
      - name: Deploy Allure report to GitHub Pages
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
          publish_branch: gh-pages
          destination_dir: allure/${{ github.run_number }}
          force_orphan: false