    - name: Run Playwright tests
      run: npx playwright test

    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30

    # Publicar el reporte Playwright en GitHub Pages (¡ya no necesitas show-report!)
    - name: Deploy Playwright report to GitHub Pages
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./playwright-report
        publish_branch: gh-pages
        destination_dir: playwright/${{ github.run_number }}
        force_orphan: false

    - name: Generate Allure report
      run: npx allure generate --clean

    - name: Deploy Allure report to GitHub Pages
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./allure-report
        publish_branch: gh-pages
        destination_dir: allure/${{ github.run_number }}
        force_orphan: false
